### ISSUE TITLE
Not working on 2.2.1 release

### ISSUE THREAD

**Issue by lokspel** [purpurcof/Identica-CommandBlocker#3]
[20:34:46 ERROR]: Couldn't pass ProxyInitializeEvent to identica-commandblocker 1.4.0
java.lang.NoClassDefFoundError: me/whereareiam/configura/merge/defaults/DefaultsProvider
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:962) ~[?:?]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:144) ~[?:?]
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:454) ~[?:?]
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:367) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[server.jar:4.1.2-SNAPSHOT (git-21bbf35d-b27)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[server.jar:4.1.2-SNAPSHOT (git-21bbf35d-b27)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490) ~[?:?]
        at me.purpurcof.identica.addon.commandblocker.config.CommandBlockerConfiguration.<init>(CommandBlockerConfiguration.java:20) ~[?:?]
        at me.purpurcof.identica.addon.commandblocker.velocity.VelocityCommandBlockerPlugin.onProxyInitialize(VelocityCommandBlockerPlugin.java:69) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:4.1.2-SNAPSHOT (git-21bbf35d-b27)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:677) ~[server.jar:4.1.2-SNAPSHOT (git-21bbf35d-b27)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:542) ~[server.jar:4.1.2-SNAPSHOT (git-21bbf35d-b27)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1474) [?:?]
Caused by: java.lang.ClassNotFoundException: me.whereareiam.configura.merge.defaults.DefaultsProvider
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[server.jar:4.1.2-SNAPSHOT (git-21bbf35d-b27)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[server.jar:4.1.2-SNAPSHOT (git-21bbf35d-b27)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490) ~[?:?]
        ... 17 more

**Comment by purpurcof** [comment]
You need use https://github.com/whereareiam/Identica/actions/runs/27468563615
